# Generated by Django 4.0.5 on 2022-07-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='created_at',
        ),
    ]
