# Generated by Django 4.0.5 on 2022-08-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_alter_audio_options_audio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
