# Generated by Django 4.0.5 on 2022-08-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_alter_audio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Sunday Sermons'), ('2', 'Bible Studies'), ('3', 'Thursday Prayers')], max_length=100),
        ),
    ]
