# Generated by Django 4.0.5 on 2022-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_alter_audio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('year_of_office', models.CharField(max_length=1000)),
            ],
        ),
    ]
